name: ComposeAdvanced

on:
  push:
    branches:
      - main
    paths:
      - 'ComposeAdvanced/**'
      - '.github/workflows/ComposeAdvanced.yml'
  pull_request:
    paths:
      - 'ComposeAdvanced/**'
      - '.github/workflows/ComposeAdvanced.yml'

env:
  SAMPLE_PATH: ComposeAdvanced

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: check --stacktrace
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: |
            ${{ env.SAMPLE_PATH }}/app/build/outputs

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: |
            ${{ env.SAMPLE_PATH }}/app/build/reports

  apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: app:assembleRelease
          build-root-directory: ${{ env.SAMPLE_PATH }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: App
          path: ${{ env.SAMPLE_PATH }}/app/build/outputs/apk/release/app-release.apk
